apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deploy
spec:
  selector:
    matchLabels:
      app: web-simple-deploy
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web-simple-deploy
    spec:
      containers:
      - name: simple-deployment-k8s
        image: jnavarro447/k8s-deploy:latest
        ports:
        - containerPort: 80
