apiVersion: v1
kind: Service
metadata:
  name: simple-app-deploy
  labels:
    app: web-simple-deploy
spec:
  selector:
    app: web-simple-deploy
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
